environment:
  ports:
    main: 9090
    signalling: 2323
    cms: 6969
    sia-dcs: 4556
    masxml: 6667
    sbn: 6677
    manitou: 6777
    dummy: 9999

logging:
  level: INFO  # Можливо: DEBUG, INFO, WARNING, ERROR, CRITICAL, TRACE
