environment:
  ports:
    main: 9090
    signalling: 2323
    cms: 6969
    sia_dcs: 4556
    cms_masxml: 6667
    cms_sbn: 6677
    cms_manitou: 6777
    dummy: 9999

logging:
  level: DEBUG  # Можливо: DEBUG, INFO, WARNING, ERROR, CRITICAL, TRACE
